spring:
  profile:
    active: ${PROFILE}
  application:
    name: AssetCare

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
        globally_quoted_identifiers: true
  mvc:
    format:
      date-time: iso

  liquibase:
    enabled: true
    change-log: "classpath:/liquibase/changelog-master.yaml"

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
server:
  port: ${SERVER_PORT}

debug: false

cache:
  caffeine:
    initial-capacity: 100
    maximum-size: 500
    expire-after-write-seconds: 300

logging:
  level:
    root: INFO
    # liquibase: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
    com:
      knits:
        enterprise: DEBUG

edm:
  secret: ${JWT_SECRET}
  issuer: "Enterprise Data Management System"
  jwt-expiration-millis: ${JWT_EXPIRATION}
  init-data: ${INIT_DATA}